# Generated by Django 3.0.2 on 2020-01-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='users.Customuser')),
                ('name', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
